### ISSUE TITLE
can't make the good result using real time processing data

### ISSUE THREAD

**Issue by carl1218** [googlecartographer/cartographer_ros#245]
Hi,
  My CPU is intel i7-4710HQ , 4G memory,and i runed thedemo_backpack_2d bag
the effect is very good，Run smoothly and the map does not overlap,But when i run it using real time  data,can't make the good result and the map will overlap，I'm not using IMU data and i keep the laser level.If  test only one or two rooms（Each room area  is 4m*7m）,the effect is very good ，But if test more than two rooms the effect is not ideal，the map will overlap，i using HOKUYO URG-04LX ,  The frequency of this laser is only 10 Hz, scanning distance is only about 5.6 meters，What triggered off the error? 
Is it scan frequency is not high or scan distance is not enough？

This is map：
![Uploading 123.JPG…]()

**Comment by carl1218** [comment]
![img_1723](https://cloud.githubusercontent.com/assets/17962046/21584115/861a089a-d0d6-11e6-93e2-16bb44c95afb.JPG)

**Comment by damonkohler** [comment]
Thank you for filing an issue!

It would help us tremendously if you provide the following so that we can easily
reproduce your issue:

1. A link to a Git repository containing a branch of `cartographer_ros`
   containing all the configuration, launch, and URDF files required to
   reproduce your issue.
2. A link to a bag file we can use to reproduce your issue.

We will likely be unable to help you without both.

**Comment by carl1218** [comment]
@damonkohler 
I using HOKUYO URG-04LX

This is urdf:

```
<robot name="cartographer_backpack_2d">
<link name="base_link"/>
<link name="laser"/>
<joint name="laser_joint" type="fixed">
    <parent link="base_link" />
    <child link="laser" />
    <origin xyz="0 0 0" rpy="0 0 0" />
</joint>
</robot>
```
This is lua:

```
include "map_builder.lua"
options = {
  map_builder = MAP_BUILDER,
  map_frame = "map",
  tracking_frame = "laser_link",
  published_frame = "laser_link",
  odom_frame = "odom",
  provide_odom_frame = true,
  use_odometry = false,
  use_laser_scan = true,
  use_multi_echo_laser_scan = false,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
}

MAP_BUILDER.use_trajectory_builder_2d = true

TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.linear_search_window = 0.15
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.angular_search_window = math.rad(35.)

SPARSE_POSE_GRAPH.optimization_problem.huber_scale = 1e2
```
This is launch:
```
<node name="cartographer_node" pkg="cartographer_ros"
    type="cartographer_node" args="
        -configuration_directory $(find cartographer_ros)/configuration_files
        -configuration_basename backpack_2d.lua
       --urdf_filename $(find cartographer_ros)/urdf/backpack_2d.urdf"
    output="screen">
  <remap from="scan" to="/laser_scan" />

</node>
   <node name="rviz" pkg="rviz" type="rviz" required="true"
    args="-d $(find cartographer_ros)/configuration_files/demo_2d.rviz" />

</launch>
```

**Comment by carl1218** [comment]
I only using HOKUYO URG-04LX,can't make the good result.

A link about a bag file：
https://drive.google.com/file/d/0B33M6O52cUeNRjdmS1Mydk5Sa1k/view?usp=sharing

A link about backpack_2d.urdf：https://drive.google.com/file/d/0B33M6O52cUeNbjNqSmZoV1dHaEU/view?usp=sharing

A link about hokuyo launch：https://drive.google.com/file/d/0B33M6O52cUeNWTY3Z0plZ0RlUVk/view?usp=sharing

A link about hokuyo.lua：https://drive.google.com/file/d/0B33M6O52cUeNVjJ4WmdzZWplbGM/view?usp=sharing

**Comment by SirVer** [comment]
Thanks for providing the files. I tuned your configuration in the last few commits in [this branch](https://github.com/SirVer/cartographer_ros/commits/user/carl1218). 

There were a few issues here:

1) Your bag file contained not only sensor data, but also prior Cartographer topics - like submap meta data. That confused the current run. I filtered your bag to only contain your laser data: `rosbag filter my.bag only-tf.bag "topic == '/laser'`.
3) Your `urdf` is based on `base_link`, but you told Cartographer to track `laser`. The tracking frame therefore was never displayed in rViz.

In the end I only needed to tune loop closure to only accept really high quality scan matches. The default settings you were using produced many matches (since the laser is quite good) and many of them were not correct - i.e. it matched the two neighboring rooms because they looked "similar enough" to Cartographer. 

If you check out my branch I linked above, you should get everything running with `roslaunch cartographer_ros hokuyo_bag.launch bag_filename:=2017-01-08-22-52-34.filtered.bag` using the filtered bag created above. This gives this result for me:

![2017-01-09-164739_1918x1179_scrot](https://cloud.githubusercontent.com/assets/140115/21772419/6f58a6ec-d68b-11e6-9a27-15fcffb5b996.png)

**Comment by carl1218** [comment]
Thank you very much,how can i tune loop closure?

**Comment by carl1218** [comment]
@SirVer 
Hi,
   This time I did not use URDF. I've record a new bag,and i filtered my bag to only contain the laser data,and running the filterd bag,But the effect still not good.how can i tune loop closure？

this is launch:
https://drive.google.com/file/d/0B33M6O52cUeNb3F3SmFtdnp1NFU/view?usp=sharing
this is bag launch:
https://drive.google.com/file/d/0B33M6O52cUeNMVUyRWUzZmdjVHM/view?usp=sharing
this is lua:
https://drive.google.com/file/d/0B33M6O52cUeNN0t0cGlKVXVBNnM/view?usp=sharing
this is bag：
https://drive.google.com/file/d/0B33M6O52cUeNRS1QUGdkRkY2T3M/view?usp=sharing
this is filtered bag:
https://drive.google.com/file/d/0B33M6O52cUeNVFBRbjdZX21IZGc/view?usp=sharing

**Comment by SirVer** [comment]
Carl, I linked you my branch. Look at the last few commits to see what I changed for loop closure: https://github.com/SirVer/cartographer_ros/commits/user/carl1218
