### ISSUE TITLE
messy map

### ISSUE THREAD

**Issue by gavinwtaylor** [googlecartographer/cartographer_ros#279]
I'm a professor, and I'm trying to get a map built of our hallway, hoping to use it for some cool projects later in the course.  I'm using turtlebots with depth sensors, and unfortunately, I'm not getting a very good map.  I was hoping somebody with some insight into configuration settings would be willing to help me out.  The run with the default settings was pretty bad, but given that it was a trajectory with a lot of turns, I turned up the motion filter's max_angle_radians to .8 which made it much better but still quite some distance from usable.  [All configuration files can be found here](https://github.com/gavinwtaylor/cartographyFiles).  [The bag file can be downloaded here](https://www.usna.edu/Users/cs/taylor/turny.bag) (~1G).

Any help in saving my class would be greatly appreciated!

EDIT: [Made a second bag with fewer turns](https://www.usna.edu/Users/cs/taylor/lessTurny.bag).  This one gives me a map with different problems.

EDIT: I'm having my best luck with the second bag, in 3d (to widen the FOV).  If anybody's feeling generous, I could still use some guidance on parameter choosing.

**Comment by SirVer** [comment]
Your Git directory does not contain any history and is not a fork of the Cartographer repositories. So it is unclear what changes you actually did to your configuration. Consequently, it is unclear to me which launch file and configuration you actually used for running your tests.

I'd rather not reverse engineer your URDF and your frames, so I will not further investigate for now. Please provide launch commands, urdf, configuration files and ideally a fork for cartographer and cartographer_ros so that I can see what you tried already.

**Comment by SirVer** [comment]
Closing as stale.
