### ISSUE TITLE
Question about the alpha vector

### ISSUE THREAD

**Issue by GMahmoud** [googlecartographer/cartographer_ros#520]
Hey guys,
I am trying to visualize the submaps of cartographer for  Android device. 
And I have a quick question concerning the signification of the alpha vector in the submap. Does it represent the opacity ?  In the Ogre texture you used PF_BYTE_RGB as parameter and I am using argb32 as codec for my texture. I don't know how to fuse all the submaps to get a global map. I put the alpha value but it get only borders (no clearing of the map).
![with android](https://user-images.githubusercontent.com/29754310/31185644-cb6ddb2c-a92c-11e7-93ec-3d3fdccc6f3b.png)
![with ros](https://user-images.githubusercontent.com/29754310/31185643-cb68b8cc-a92c-11e7-815a-df67933f8082.png)

**Comment by wohe** [comment]
Our textures only use value (premultiplied alpha) and alpha (representing opacity as you say). If I remember correctly we use an RGB texture with Ogre because RG texture was not possible or caused issues with Ogre. If you look at `ogre_submap.cc`, you see that we store the value in R and the alpha in G, and read it from there in the shader `submap.frag`. Does that answer your question?

**Comment by Mofef** [comment]
We had once the same issue/confusion.
If you want resemble the compositing of submaps like in rviz using normal alpha-blending you first need to transform the given "alpha" and "value" values like so:
(assuming everything is in float normalized to 0. ...1.)
*    `initialize the output to the same shape as the input (i.e. width * height * 2 channels)`
*    `result[alpha] = input[alpha] + input[value]`
*    `result[value] = 1.0 where input[value]>input[alpha] otherwise 0.0`

Afterwards you can just apply the over operator as in https://en.wikipedia.org/wiki/Alpha_compositing.

**Comment by wohe** [comment]
I strongly suggest to use premultiplied alpha for best visual quality. Any reason not to simply change the blend function? If you want to use RGBA you just copy (value, value, value, alpha) into the texture.

**Comment by GMahmoud** [comment]
Thank you guys (@wohe and @Mofef)  for your answers. 
I checked my texture with your information and I got better result.
So glad.

Cheers,
MG.
![with unity](https://user-images.githubusercontent.com/29754310/31236538-a3060524-a9f4-11e7-8838-a1f3ddb23816.png)

Here's a new screenshot. I think I can close this issue ;)
