### ISSUE TITLE
2d map and trajectory works, TF map --> base_link does not - using only laserscan data

### ISSUE THREAD

**Issue by Magnusgaertner** [googlecartographer/cartographer_ros#758]
Hey everyone, I am facing the same issue as #472.

building a 2d map and trajectory from only laserscan data works fine, but the published Transformation map/odom --> base_link is rotating and floating around with almost infinite distance to the map origin. 

Link to the rosbag to reproduce:
https://drive.google.com/file/d/1iFKOvSmUErf_HELaoGcEezGcd9cHn-V-/view?usp=sharing

Running rosbag_validate produces:
https://gist.github.com/Magnusgaertner/5ef6da90e451d08dcb6dab9ab1df82ff.js

Link to install_isolated/share/cartographer and install_isolated/share/cartographer_ros:
https://github.com/Magnusgaertner/cartographer_issue

**Comment by gaschler** [comment]
> E0307 18:03:15.739637 15483 rosbag_validate_main.cc:342] frame_id "velodyne" on topic /scan has serialization time 1520442024.248148996 but sensor time 1519148044.552604000 differing by -1.29398e+06 s

Your `ros::Time` (serialization time of message) vastly differs from the header timestamps of the sensor data.
Cartographer only looks at the sensor data and creates a map, but the extrapolation for the `tf` output in cartographer_ros will be completely off because it is based on both timestamps. This is known and should be fixed by providing input data where the timestamps match.

**Comment by Magnusgaertner** [comment]
thanks :)
